// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5WTQsto0T341Q1jdRszp0J1vzoABidjY',
    appId: '1:133815046722:android:37f1e619fc2a9ae838d3db',
    messagingSenderId: '133815046722',
    projectId: 'nanolaminate-8fd37',
    databaseURL: 'https://nanolaminate-8fd37-default-rtdb.firebaseio.com',
    storageBucket: 'nanolaminate-8fd37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx0c1dIzvrd7kcqOKc4RApnlHjhoXr1gk',
    appId: '1:133815046722:ios:9b63a7ed28acce6738d3db',
    messagingSenderId: '133815046722',
    projectId: 'nanolaminate-8fd37',
    databaseURL: 'https://nanolaminate-8fd37-default-rtdb.firebaseio.com',
    storageBucket: 'nanolaminate-8fd37.appspot.com',
    iosClientId: '133815046722-vqa83bdnsdbraupictrbg4q5cilf74qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanoLaminate',
  );
}
